name: plocabot_environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - setuptools
  - wheel
  - flask
  - flask-cors
  - spacy
  - transformers
  - numpy
  - tqdm
  - requests
  - beautifulsoup4
  - lxml
  - pyyaml
  - sympy
  - joblib
  - networkx
  - click
  - regex
  - packaging
  - charset-normalizer
  - idna
  - urllib3
  - certifi
  - pip:
      - annotated-types==0.7.0
      - blinker==1.9.0
      - blis==1.2.0
      - catalogue==2.0.10
      - cloudpathlib==0.21.0
      - confection==0.1.5
      - configparser==7.2.0
      - cymem==2.0.11
      - deep-translator==1.11.4
      - filelock==3.17.0
      - h11==0.9.0
      - h2==3.2.0
      - hpack==3.0.0
      - hstspreload==2025.1.1
      - httpcore==0.9.1
      - httpx==0.13.3
      - huggingface-hub==0.28.1
      - hyperframe==5.2.0
      - importlib-metadata==8.6.1
      - itsdangerous==2.2.0
      - jinja2==3.1.5
      - langcodes==3.5.0
      - language-data==1.3.0
      - libretranslatepy==2.1.1
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - murmurhash==1.0.12
      - nltk==3.9.1
      - preshed==3.0.9
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pymongo
      - rfc3986==1.5.0
      - rich==13.9.4
      - safetensors==0.5.2
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - smart-open==7.1.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - thinc==8.3.4
      - tokenizers==0.21.0
      - torch==2.6.0
      - typer==0.15.2
      - typing-extensions==4.12.2
      - wasabi==1.1.3
      - weasel==0.4.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - zipp==3.21.0